/**
 * STRATEGY SEARCH — Candidate Generation & Mutation
 *
 * Generates strategy candidates by crossing:
 *   constraints × patterns × mechanisms
 *
 * Mutation: swap pattern, shift mechanism, or change operator fit.
 */

import type { StructuralProfile } from "@/lib/reconfiguration/structuralProfile";
import type { ConstraintCandidate } from "@/lib/constraintDetectionEngine";
import { STRUCTURAL_PATTERNS } from "@/lib/reconfiguration/patternLibrary";
import type { StrategyCandidate, StrategyFeatures } from "./types";
import { matchAnalogies, analogiesToCandidates } from "./analogyMatcher";

let _counter = 0;
function nextId(): string {
  return `strat-${Date.now()}-${++_counter}`;
}

// ═══════════════════════════════════════════════════════════════
//  MECHANISM TEMPLATES — How patterns resolve constraints
// ═══════════════════════════════════════════════════════════════

const MECHANISM_TEMPLATES: Record<string, string[]> = {
  aggregation: [
    "Build a unified platform that consolidates fragmented providers into a single discovery and booking interface",
    "Create a comparison marketplace that reduces buyer search costs across scattered options",
    "Aggregate demand to give small suppliers collective bargaining power",
  ],
  unbundling: [
    "Decompose the bundled offering into standalone components, selling only the high-value piece",
    "Strip out the premium component and sell it independently at higher margins",
    "Let customers buy only what they need — eliminate forced cross-subsidy",
  ],
  rebundling: [
    "Reassemble fragmented point solutions around the actual job-to-be-done",
    "Create an integrated workflow that spans currently separate product categories",
    "Build a unified experience that eliminates the integration tax between tools",
  ],
  supply_chain_relocation: [
    "Move downstream to own the customer relationship, bypassing intermediaries",
    "Move upstream to control supply quality and cost",
    "Relocate distribution to digital channels, eliminating physical constraints",
  ],
  stakeholder_monetization: [
    "Monetize the data generated by operations — sell insights to adjacent stakeholders",
    "Create a second revenue stream from the audience/traffic the business already attracts",
    "Convert a cost center (training, compliance, QA) into a sellable service",
  ],
  infrastructure_abstraction: [
    "Extract the core operational capability into a shared platform others can use",
    "Codify expert knowledge into a software system that replaces manual expertise",
    "Build the industry's missing backend — scheduling, compliance, or logistics as a service",
  ],
  demand_reframing: [
    "Redefine the product's job-to-be-done to access a larger buyer population",
    "Shift from selling to professionals to selling to consumers by simplifying the interface",
    "Reframe the value proposition from cost savings to risk reduction or status",
  ],
  outcome_pricing: [
    "Price on the measurable outcome created for the customer, not the inputs consumed",
    "Shift from hourly/project billing to success-fee or performance-based pricing",
    "Guarantee results and charge a premium — absorb downside risk for upside margin",
  ],
  network_effect: [
    "Build a data flywheel where more usage creates better predictions for all users",
    "Create a community layer where each new member increases value for existing members",
    "Design protocol-level lock-in where more adopters make switching structurally impossible",
  ],
  vertical_integration: [
    "Acquire or build the upstream supply layer to control quality and capture margin",
    "Move downstream into distribution to own the customer relationship",
    "Integrate adjacent services into a full-stack offering that competitors can't match",
  ],
  regulatory_arbitrage: [
    "Enter through a regulatory gap that incumbents are too large or slow to exploit",
    "Build compliance-as-a-service for an industry drowning in regulatory overhead",
    "Pre-position for upcoming regulatory changes that will reshape the competitive landscape",
  ],
  freemium_flip: [
    "Give away the core product to build distribution, monetize through premium features",
    "Invert the revenue model — make the hardware free, charge for consumables/services",
    "Use free tier to create massive adoption, then monetize data or enterprise features",
  ],
  temporal_arbitrage: [
    "Pre-build infrastructure for a shift that's 12-18 months away from mainstream adoption",
    "Move faster than incumbents to lock up customers during a transition window",
    "Exploit seasonal or cyclical timing mismatches that create temporary pricing power",
  ],
  loss_leader_ecosystem: [
    "Subsidize the initial purchase to capture the customer, monetize recurring consumables",
    "Give away the platform, charge for the ongoing ecosystem of services and add-ons",
    "Use below-cost entry pricing to build switching costs, then expand share of wallet",
  ],
  data_moat: [
    "Collect proprietary data through operations that compounds into un-replicable advantage",
    "Build a feedback loop where product usage generates data that improves the product",
    "Create an intelligence layer that no competitor can replicate without equivalent scale",
  ],
};

// ═══════════════════════════════════════════════════════════════
//  PATTERN → FEATURE MAPPING
// ═══════════════════════════════════════════════════════════════

function patternToFamily(patternId: string): StrategyFeatures["patternFamily"] {
  const map: Record<string, StrategyFeatures["patternFamily"]> = {
    aggregation: "supply_side",
    unbundling: "supply_side",
    rebundling: "supply_side",
    supply_chain_relocation: "integration",
    stakeholder_monetization: "supply_side",
    infrastructure_abstraction: "supply_side",
    demand_reframing: "demand_side",
    outcome_pricing: "pricing",
    network_effect: "network",
    vertical_integration: "integration",
    regulatory_arbitrage: "timing",
    freemium_flip: "pricing",
    temporal_arbitrage: "timing",
    loss_leader_ecosystem: "pricing",
    data_moat: "network",
  };
  return map[patternId] ?? "supply_side";
}

function patternToRevenue(patternId: string): StrategyFeatures["revenueShift"] {
  const map: Record<string, StrategyFeatures["revenueShift"]> = {
    aggregation: "marketplace",
    outcome_pricing: "outcome",
    freemium_flip: "freemium",
    network_effect: "recurring",
    loss_leader_ecosystem: "ecosystem",
    stakeholder_monetization: "recurring",
    infrastructure_abstraction: "recurring",
  };
  return map[patternId] ?? "none";
}

function patternToMoat(patternId: string): StrategyFeatures["moatType"] {
  const map: Record<string, StrategyFeatures["moatType"]> = {
    network_effect: "network_effect",
    data_moat: "data",
    vertical_integration: "scale",
    regulatory_arbitrage: "regulatory",
    loss_leader_ecosystem: "switching_cost",
    demand_reframing: "brand",
  };
  return map[patternId] ?? "none";
}

function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// ═══════════════════════════════════════════════════════════════
//  CANDIDATE GENERATION
// ═══════════════════════════════════════════════════════════════

/**
 * Generate initial population by crossing constraints × patterns.
 * Each constraint gets tested against every pattern, generating
 * candidates only where the pattern structurally qualifies.
 */
export function generateInitialPopulation(
  profile: StructuralProfile,
  populationSize: number,
): StrategyCandidate[] {
  const candidates: StrategyCandidate[] = [];
  const constraints = profile.bindingConstraints;

  if (constraints.length === 0) return [];

  // Cross every constraint with every pattern
  for (const constraint of constraints) {
    for (const pattern of STRUCTURAL_PATTERNS) {
      const qualification = pattern.qualifies(profile);
      if (!qualification.qualifies) continue;

      const mechanisms = MECHANISM_TEMPLATES[pattern.id] ?? [pattern.mechanism];
      // Generate 1-2 candidates per constraint-pattern pair
      const mechCount = Math.min(2, mechanisms.length);
      for (let i = 0; i < mechCount; i++) {
        candidates.push({
          id: nextId(),
          constraintId: constraint.constraintName,
          constraintName: constraint.explanation,
          patternId: pattern.id,
          patternName: pattern.name,
          mechanism: mechanisms[i],
          operatorFit: profile.etaActive ? "eta" : "any",
          features: {
            constraintCategory: constraint.constraintName.split("_")[0] ?? "general",
            patternFamily: patternToFamily(pattern.id),
            revenueShift: patternToRevenue(pattern.id),
            distributionChange: inferDistributionChange(pattern.id),
            moatType: patternToMoat(pattern.id),
            timeHorizon: inferTimeHorizon(pattern.id),
          },
        });
      }
    }
  }

  // If we have more candidates than needed, sample randomly
  if (candidates.length > populationSize) {
    const shuffled = [...candidates].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, populationSize);
  }

  // If we have fewer, generate fresh variants
  while (candidates.length < populationSize && candidates.length > 0) {
    const parent = pickRandom(candidates);
    candidates.push(mutateCandidate(parent, profile));
  }

  return candidates;
}

/**
 * Mutate a strategy candidate — swap mechanism, adjust features, or shift pattern.
 */
export function mutateCandidate(
  parent: StrategyCandidate,
  profile: StructuralProfile,
): StrategyCandidate {
  const roll = Math.random();

  if (roll < 0.4) {
    // Swap mechanism
    const mechanisms = MECHANISM_TEMPLATES[parent.patternId] ?? [parent.mechanism];
    const newMech = mechanisms.length > 1
      ? pickRandom(mechanisms.filter(m => m !== parent.mechanism))
      : parent.mechanism;
    return { ...parent, id: nextId(), mechanism: newMech };
  }

  if (roll < 0.7) {
    // Swap pattern (keeping constraint)
    const qualifiedPatterns = STRUCTURAL_PATTERNS.filter(p => p.qualifies(profile).qualifies);
    if (qualifiedPatterns.length > 1) {
      const newPattern = pickRandom(qualifiedPatterns.filter(p => p.id !== parent.patternId));
      const mechanisms = MECHANISM_TEMPLATES[newPattern.id] ?? [newPattern.mechanism];
      return {
        ...parent,
        id: nextId(),
        patternId: newPattern.id,
        patternName: newPattern.name,
        mechanism: pickRandom(mechanisms),
        features: {
          ...parent.features,
          patternFamily: patternToFamily(newPattern.id),
          revenueShift: patternToRevenue(newPattern.id),
          moatType: patternToMoat(newPattern.id),
          distributionChange: inferDistributionChange(newPattern.id),
        },
      };
    }
  }

  // Mutate features
  const features = { ...parent.features };
  const timeOptions: StrategyFeatures["timeHorizon"][] = ["immediate", "short", "medium", "long"];
  features.timeHorizon = pickRandom(timeOptions.filter(t => t !== features.timeHorizon));
  return { ...parent, id: nextId(), features };
}

/**
 * Generate a completely fresh candidate from available materials.
 */
export function generateFreshCandidate(
  profile: StructuralProfile,
): StrategyCandidate | null {
  const qualifiedPatterns = STRUCTURAL_PATTERNS.filter(p => p.qualifies(profile).qualifies);
  if (qualifiedPatterns.length === 0 || profile.bindingConstraints.length === 0) return null;

  const pattern = pickRandom(qualifiedPatterns);
  const constraint = pickRandom(profile.bindingConstraints);
  const mechanisms = MECHANISM_TEMPLATES[pattern.id] ?? [pattern.mechanism];

  return {
    id: nextId(),
    constraintId: constraint.constraintName,
    constraintName: constraint.explanation,
    patternId: pattern.id,
    patternName: pattern.name,
    mechanism: pickRandom(mechanisms),
    operatorFit: profile.etaActive ? "eta" : "any",
    features: {
      constraintCategory: constraint.constraintName.split("_")[0] ?? "general",
      patternFamily: patternToFamily(pattern.id),
      revenueShift: patternToRevenue(pattern.id),
      distributionChange: inferDistributionChange(pattern.id),
      moatType: patternToMoat(pattern.id),
      timeHorizon: inferTimeHorizon(pattern.id),
    },
  };
}

function inferDistributionChange(patternId: string): StrategyFeatures["distributionChange"] {
  const map: Record<string, StrategyFeatures["distributionChange"]> = {
    supply_chain_relocation: "direct",
    aggregation: "platform",
    network_effect: "network",
    vertical_integration: "vertical",
    freemium_flip: "direct",
  };
  return map[patternId] ?? "none";
}

function inferTimeHorizon(patternId: string): StrategyFeatures["timeHorizon"] {
  const map: Record<string, StrategyFeatures["timeHorizon"]> = {
    temporal_arbitrage: "immediate",
    outcome_pricing: "short",
    freemium_flip: "medium",
    network_effect: "long",
    data_moat: "long",
    vertical_integration: "long",
  };
  return map[patternId] ?? "medium";
}
