import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const AI_URL = "https://ai.gateway.lovable.dev/v1/chat/completions";

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { ideaName, ideaDescription, category, steeringContext, assumptionFlipped, structuralPrimitives } = await req.json();
    if (!ideaName) throw new Error("ideaName is required");

    const FIRECRAWL_API_KEY = Deno.env.get("FIRECRAWL_API_KEY");
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");
    if (!FIRECRAWL_API_KEY) throw new Error("FIRECRAWL_API_KEY not configured");

    // Build structurally-grounded search query
    const steeringKeywords = steeringContext ? ` ${steeringContext.split(/\s+/).slice(0, 5).join(" ")}` : "";
    
    // Extract structural keywords from the assumption being flipped
    const structuralKeywords = assumptionFlipped
      ? ` ${assumptionFlipped.replace(/[^a-zA-Z0-9\s]/g, "").split(/\s+/).slice(0, 8).join(" ")}`
      : "";
    
    // Include structural primitives as search terms (e.g. "subscription model", "direct-to-consumer")
    const primitivesKeywords = structuralPrimitives?.length
      ? ` ${structuralPrimitives.slice(0, 3).join(" ")}`
      : "";

    const query = `${ideaName} ${category || ""}${structuralKeywords}${primitivesKeywords}${steeringKeywords} competitor similar business startup`;

    const searchRes = await fetch("https://api.firecrawl.dev/v1/search", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${FIRECRAWL_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query, limit: 8, scrapeOptions: { formats: ["markdown"] } }),
    });

    if (!searchRes.ok) {
      const errText = await searchRes.text();
      throw new Error(`Firecrawl search failed (${searchRes.status}): ${errText}`);
    }

    const searchData = await searchRes.json();
    const results = searchData?.data || [];

    // Build concise context from search results
    const context = results
      .filter((r: any) => r.url && r.markdown)
      .map((r: any) => `URL: ${r.url}\nTitle: ${r.title || ""}\n${r.markdown.slice(0, 800)}`)
      .join("\n---\n")
      .slice(0, 6000);

    const sourceUrls = results
      .filter((r: any) => r.url)
      .map((r: any) => r.url)
      .join("\n");

    // Build structural context block for AI prompt
    const structuralContext = [
      assumptionFlipped ? `ASSUMPTION BEING FLIPPED: "${assumptionFlipped}"` : "",
      structuralPrimitives?.length ? `STRUCTURAL PRIMITIVES TARGETED: ${structuralPrimitives.join(", ")}` : "",
    ].filter(Boolean).join("\n");

    const aiRes = await fetch(AI_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${LOVABLE_API_KEY}` },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "user",
            content: `I'm validating a new business idea that was generated by FLIPPING a structural assumption:

Name: ${ideaName}
Description: ${ideaDescription || "N/A"}
Category: ${category || "N/A"}
${structuralContext ? `\n${structuralContext}\n` : ""}
Here are web search results about similar businesses:

${context}

Source URLs:
${sourceUrls}

Identify 3-5 REAL companies or products that are STRUCTURALLY similar — meaning they exploit the same structural inversion, target the same primitive (e.g. removing an intermediary, flipping ownership model, inverting the pricing mechanism), or challenge the same industry assumption. Do NOT just match by name or surface-level category.

For each, return ONLY:
- "name": Company/product name
- "url": Their actual website URL (from the search results)
- "description": One sentence on what structural similarity they share with this idea (which assumption they also challenge or which primitive they also exploit)
- "competition_score": 1-10 integer (10 = exploits the exact same structural inversion, 1 = loosely related by category only)
- "structural_overlap": One phrase describing the shared structural mechanism (e.g. "removes broker intermediary", "subscription replaces ownership", "peer-to-peer bypasses central authority")

Return ONLY a valid JSON array. Only include genuinely structurally similar businesses with real URLs from the research. If fewer than 3 are relevant, return fewer.

[{"name":"...","url":"...","description":"...","competition_score":7,"structural_overlap":"..."}]`,
          },
        ],
        temperature: 0.3,
        max_tokens: 1500,
      }),
    });

    if (!aiRes.ok) {
      if (aiRes.status === 429) return new Response(JSON.stringify({ error: "Rate limit exceeded. Try again shortly." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      if (aiRes.status === 402) return new Response(JSON.stringify({ error: "AI credits exhausted." }), { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      throw new Error(`AI error ${aiRes.status}`);
    }

    const aiData = await aiRes.json();
    const raw = aiData.choices?.[0]?.message?.content || "[]";
    const cleaned = raw.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();

    let competitors;
    try {
      competitors = JSON.parse(cleaned);
      if (!Array.isArray(competitors)) competitors = competitors.competitors || competitors.data || [];
    } catch {
      competitors = [];
    }

    // Normalize to schema
    competitors = competitors.map((c: any) => ({
      name: c.name || "Unknown",
      url: c.url || "",
      description: c.description || "",
      competition_score: c.competition_score || c.direct_competition_score || 5,
      structural_overlap: c.structural_overlap || "",
    }));

    return new Response(JSON.stringify({ success: true, competitors }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("scout-competitors error:", err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
