/**
 * Due Diligence Killer Questions
 * 
 * Dynamically generated from biExtraction signals — constraints, leverage points,
 * cost drivers, revenue sources, workflows, and financial inputs are all mapped
 * to specific question templates. Every data-triggered question shows its source.
 */

import { memo, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Crosshair, ChevronDown, ChevronUp, AlertTriangle, Users, DollarSign,
  Shield, Building, TrendingDown, Copy, Check, Settings, Zap,
} from "lucide-react";
import { extractFinancialInputs } from "@/lib/etaScoringEngine";
import { generateDDQuestions, getDDStats, type DDCategory, type DDQuestion } from "@/lib/ddQuestionEngine";

const ICON_MAP: Record<string, React.ReactNode> = {
  DollarSign: <DollarSign size={13} />,
  Users: <Users size={13} />,
  Building: <Building size={13} />,
  Settings: <Settings size={13} />,
  Shield: <Shield size={13} />,
  TrendingDown: <TrendingDown size={13} />,
  Crosshair: <Crosshair size={13} />,
};

interface DueDiligenceQuestionsProps {
  biExtraction: Record<string, any> | null;
  governedData: Record<string, any> | null;
}

const SEVERITY_STYLES = {
  critical: { bg: "hsl(var(--destructive) / 0.08)", border: "hsl(var(--destructive) / 0.25)", text: "hsl(var(--destructive))", label: "CRITICAL" },
  high: { bg: "hsl(var(--warning, 38 92% 50%) / 0.08)", border: "hsl(var(--warning, 38 92% 50%) / 0.25)", text: "hsl(38, 92%, 45%)", label: "HIGH" },
  medium: { bg: "hsl(var(--muted) / 0.5)", border: "hsl(var(--border))", text: "hsl(var(--muted-foreground))", label: "MEDIUM" },
};

export const DueDiligenceQuestions = memo(function DueDiligenceQuestions({
  biExtraction,
  governedData,
}: DueDiligenceQuestionsProps) {
  const inputs = useMemo(
    () => extractFinancialInputs(governedData, biExtraction),
    [biExtraction, governedData],
  );
  const categories = useMemo(() => generateDDQuestions(inputs, biExtraction), [inputs, biExtraction]);
  const stats = useMemo(() => getDDStats(categories), [categories]);
  const [expandedCat, setExpandedCat] = useState<string | null>("killer");
  const [copiedIdx, setCopiedIdx] = useState<string | null>(null);

  const handleCopy = (question: string, id: string) => {
    navigator.clipboard.writeText(question);
    setCopiedIdx(id);
    setTimeout(() => setCopiedIdx(null), 1500);
  };

  const handleCopyAll = () => {
    const criticalHighQs = categories.flatMap(cat =>
      cat.questions
        .filter(q => q.severity === "critical" || q.severity === "high")
        .map(q => ({ ...q, catLabel: cat.label }))
    );

    // Group by category for clean formatting
    const grouped = new Map<string, typeof criticalHighQs>();
    for (const q of criticalHighQs) {
      const existing = grouped.get(q.catLabel) || [];
      existing.push(q);
      grouped.set(q.catLabel, existing);
    }

    let output = `DUE DILIGENCE CHECKLIST — ${criticalHighQs.length} Critical & High Priority Questions\n${"═".repeat(60)}\n\n`;
    for (const [catLabel, questions] of grouped) {
      output += `▸ ${catLabel.toUpperCase()}\n${"-".repeat(40)}\n`;
      questions.forEach((q, i) => {
        output += `☐ [${q.severity.toUpperCase()}] ${q.question}\n`;
        output += `   Why: ${q.why}\n`;
        if (q.triggerSource) output += `   ⚡ Triggered by: ${q.triggerSource}\n`;
        output += "\n";
      });
    }
    output += `${"═".repeat(60)}\nGenerated by Market Disruptor`;

    navigator.clipboard.writeText(output);
    setCopiedIdx("all");
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  const criticalHighCount = useMemo(() =>
    categories.reduce((n, cat) => n + cat.questions.filter(q => q.severity === "critical" || q.severity === "high").length, 0),
    [categories]
  );

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: 0.15 }}
      className="rounded-xl overflow-hidden"
      style={{ background: "hsl(var(--card))", border: "1px solid hsl(var(--border))" }}
    >
      {/* Header */}
      <div className="px-5 pt-4 pb-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: "hsl(var(--destructive) / 0.12)" }}>
              <Crosshair size={14} style={{ color: "hsl(var(--destructive))" }} />
            </div>
            <div>
              <h3 className="text-sm font-black text-foreground">Due Diligence Interrogation</h3>
              <p className="text-[10px] text-muted-foreground">
                {stats.totalQuestions} questions · {stats.criticalCount} critical · {stats.dataTriggeredCount} data-triggered
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {stats.dataTriggeredCount > 0 && (
              <span className="text-[9px] font-black uppercase tracking-wider px-2 py-1 rounded-md flex items-center gap-1"
                style={{ background: "hsl(var(--primary) / 0.1)", color: "hsl(var(--primary))" }}>
                <Zap size={10} />
                {stats.dataTriggeredCount} from your data
              </span>
            )}
            <button
              onClick={handleCopyAll}
              className="text-[10px] font-bold px-2 py-1 rounded-md border border-border hover:bg-muted/50 transition-colors flex items-center gap-1 text-muted-foreground"
            >
              {copiedIdx === "all" ? <Check size={10} className="text-green-600" /> : <Copy size={10} />}
              Copy All
            </button>
          </div>
        </div>
      </div>

      {/* Categories */}
      <div className="px-3 pb-4 space-y-1">
        {categories.map(cat => {
          const dataTriggeredInCat = cat.questions.filter(q => q.dataTriggered).length;
          return (
            <div key={cat.id} className="rounded-lg overflow-hidden" style={{ border: "1px solid hsl(var(--border))" }}>
              <button
                onClick={() => setExpandedCat(expandedCat === cat.id ? null : cat.id)}
                className="w-full flex items-center justify-between px-4 py-2.5 hover:bg-muted/30 transition-colors"
              >
                <div className="flex items-center gap-2">
                  <span className="text-muted-foreground">{ICON_MAP[cat.iconName] || <Crosshair size={13} />}</span>
                  <span className="text-xs font-bold text-foreground">{cat.label}</span>
                  <span className="text-[10px] font-bold text-muted-foreground">
                    ({cat.questions.length})
                  </span>
                  {dataTriggeredInCat > 0 && (
                    <span className="text-[8px] font-black uppercase tracking-wider px-1.5 py-0.5 rounded flex items-center gap-0.5"
                      style={{ background: "hsl(var(--primary) / 0.1)", color: "hsl(var(--primary))" }}>
                      <Zap size={8} />
                      {dataTriggeredInCat} DATA-TRIGGERED
                    </span>
                  )}
                </div>
                {expandedCat === cat.id ? <ChevronUp size={14} className="text-muted-foreground" /> : <ChevronDown size={14} className="text-muted-foreground" />}
              </button>

              <AnimatePresence>
                {expandedCat === cat.id && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                    className="overflow-hidden"
                  >
                    <div className="px-3 pb-3 space-y-2">
                      {cat.questions.map((q, i) => {
                        const sev = SEVERITY_STYLES[q.severity];
                        const qId = `${cat.id}-${i}`;
                        return (
                          <div
                            key={i}
                            className="rounded-lg p-3 space-y-2"
                            style={{ background: sev.bg, border: `1px solid ${sev.border}` }}
                          >
                            <div className="flex items-start justify-between gap-2">
                              <p className="text-xs font-bold text-foreground leading-snug flex-1">
                                "{q.question}"
                              </p>
                              <div className="flex items-center gap-1.5 flex-shrink-0">
                                <span className="text-[8px] font-black uppercase tracking-wider px-1.5 py-0.5 rounded" style={{ color: sev.text, background: `${sev.text}15` }}>
                                  {sev.label}
                                </span>
                                <button
                                  onClick={() => handleCopy(q.question, qId)}
                                  className="p-1 rounded hover:bg-muted/50 transition-colors"
                                  title="Copy question"
                                >
                                  {copiedIdx === qId
                                    ? <Check size={11} className="text-green-600" />
                                    : <Copy size={11} className="text-muted-foreground" />}
                                </button>
                              </div>
                            </div>
                            <p className="text-[10px] text-muted-foreground leading-snug italic">
                              Why: {q.why}
                            </p>
                            {q.triggerSource && (
                              <p className="text-[9px] font-bold flex items-center gap-1" style={{ color: "hsl(var(--primary))" }}>
                                <Zap size={9} />
                                Triggered by: {q.triggerSource}
                              </p>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>
    </motion.div>
  );
});
